from defs import *

### General ###
NEGATIVE = -1
POSITIVE = 1
TYPE = np.int64
TF_TYPE = tf.int64

### Hyper params ###
D = 6
ALPHA = 1000000 * 2**D
LR = 10

### Network  ###
HINGE_LOST_CONST = ALPHA
SECOND_LAYER_BAIS = - ALPHA
MIN_EPSILON = 1
MAX_EPSILON = 10 
STEP_EPSILON = 1
MAX_VALUE_FOR_POSITIVE_SAMPLE = 2 * abs(SECOND_LAYER_BAIS)
MIN_VALUE_FOR_NEGATIVE_SAMPLE = 0

### Learning ###
PRINT_STEP_JUMP = 1000
MAX_STEPS = 1000000

### After learning ###
PRUNE_FACTOR_WEIGHT = 10
PRUNE_FACTOR_TOTAL_NORM = 4
RECONSTRACTION_FACTOR_WEIGHT = 10
RECONSTRACTION_FACTOR_NORM = 9

### Result ###
IS_TEMP = True
TEMP_RESULT_PATH = r"tmp"
GENERAL_RESULT_PATH = r"results"
BACKUP_DIR = 'backup'
PRONE_DIR = 'prone'
PRONE_BY_MEAN_DIR = 'prone_by_mean'
ORIGINAL_FINAL_DIR = 'final'
MAX_TRY_TO_DELETE_DIR = 4